In [1]:
import numpy as np

# 1. create

In [24]:
# convert python list into numpy array
list_python = [[1,2,3],[4,5,6]]

array = np.array(list_python)

print(type(array))
print(type(list_python))


<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
# return random float values between 0 and 1 with this shape
floated_data = np.random.rand(2,5,3)

# return random integers between 0 and 19
int_data = np.random.randint(0,20, size=5)

# return array filled with zeros
zeros = np.zeros((2,2,2))

# return array filled with the value 5
full = np.full((2,2), 5)

# return array filled with ones
ones = np.ones((2,2,2))

# create array with a range
numbers = np.arange(0, 10)

# create equally spaced values
points = np.linspace(0, 100, 5)

# create identity matrix
identity = np.eye(3)


# 2. Read

In [ ]:
# return the shape of the array
print(array.shape)

# return the total number of elements
print(array.size)

# return the datatype of the elements
print(array.dtype)


(2, 3)
6
int32


In [28]:
# slicing and indexing

print(array[0])      # first row
print(array[0:2])    # first two rows
print(array[-1])     # last row
print(array[0][1])   # specific element


[1 2 3]
[[1 2 3]
 [4 5 6]]
[4 5 6]
2


# 3. Update

In [29]:
list1 = np.random.randint(1,20, size = 10)
list2 = np.random.randint(1,20, size = 10)

In [30]:
list1

array([ 7,  8,  6, 14, 19, 19, 17,  3, 19, 18])

In [31]:
list2

array([10, 10,  6,  5, 15,  8, 10, 10, 14, 11])

In [36]:
# basic math operations

addition = np.add(list1, list2)
subtraction = np.subtract(list1, list2)
multiplication = np.multiply(list1, list2)
division = np.divide(list1, list2)
power = np.power(list1, 2)
modulus = np.mod(list2, list1)


In [37]:
# statistical operations

sum_list1 = np.sum(list1)
mean_list1 = np.mean(list1)
median_list1 = np.median(list1)
std_list1 = np.std(list1)
variance_list1 = np.var(list1)
minimum = np.min(list1)
maximum = np.max(list1)


130


In [38]:
# mathematical functions

square_root = np.sqrt(list1)
square = np.square(list1)
absolute = np.abs(subtraction)
exponential = np.exp(list1)
natural_log = np.log(list1)


In [ ]:
# add values into array

list3 = np.zeros(10)

# add values at the end
list3 = np.append(list3, [10,50])
print(list3)

# insert value at specific index
list3 = np.insert(list3, 5, 15)
print(list3)


[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 10. 50.]
[ 0.  0.  0.  0.  0. 15.  0.  0.  0.  0.  0. 10. 50.]


In [ ]:
arr = np.arange(12)

# change shape of the array
reshaped = arr.reshape(3, 4)

# convert multidimensional array into 1D
flattened = reshaped.flatten()

# transpose rows and columns
transposed = reshaped.T

# 4. Delete

In [42]:
array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# np.delete(array, index, axis)
# axis = None -> flatten array
# axis = 0 -> delete row
# axis = 1 -> delete column

# delete a row
deleted_row = np.delete(array, 0, axis=0)
print(deleted_row)

# delete a column
deleted_column = np.delete(array, 1, axis=1)
print(deleted_column)
